grafana:
  adminUser: admin
  adminPassword: StrongPassword123

  persistence:
    enabled: true
    size: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

  service:
    type: ClusterIP